name: Pages Build & Publish

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_publish:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Eleventy
      run: npm install -g @11ty/eleventy

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Publish
      uses: peaceiris/actions-gh-pages@v3
      with:
        publish_dir: ./_site
        github_token: ${{ secrets.GITHUB_TOKEN }}
        cname: urtropedesigns.com
