name: Pages Build & Deploy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build_deploy:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install Eleventy
      run: npm install -g @11ty/eleventy

    - name: Install dependencies
      run: npm install
      
    - name: Build
      run: npm run build
      
    - name: Commit and Push Changes
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: "Deploy urtropedesigns.com to github.com/Urtrope-Designs/ud-site.git:gh-pages"
        branch: gh-pages
        commit_user_name: "GitHub Actions"
        commit_user_email: "actions@github.com"
        commit_author: "Author <actions@github.com>"
